using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

public enum TipoExcepcion
{
    BD_DONT_EXISTS,
    BATCH_EXCEPTION,
    TYPE_DONT_EXISTS,
    USE_DB_EXCEPTION,
    USER_DONT_EXISTS,
    VALUES_EXCEPTION,
    COLUMN_EXCEPTION,
    BD_ALREADY_EXISTS,
    TABLE_DONT_EXISTS,
    TYPE_ALREADY_EXISTS,
    USER_ALREADY_EXISTS,
    INDEX_OUT_EXCEPTION,
    TABLE_ALREADY_EXISTS,
    ARITHMETIC_EXCEPTION,
    OBJECT_ALREADY_EXISTS,
    COUNTER_TYPE_EXCEPTION,
    NULL_POINTER_EXCEPTION,
    FUNCTION_ALREADY_EXISTS,
    NUMBER_RETURNS_EXCEPTION,
    PROCEDURE_ALREADY_EXISTS
}